# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.3
loader_version=0.18.4
major_loader_version=0.18.0
# Mod Properties
mod_version=1.0.1+1.20.6
maven_group=de.hallotheengineer
archives_base_name=f5ranger
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.100.8+1.20.6


# https://modrinth.com/mod/modmenu/versions
modmenu_version=10.0.0

# https://modrinth.com/mod/cloth-config/versions
cloth_config_version=14.0.139

# https://mvnrepository.com/artifact/com.google.code.gson/gson
gson_version=2.13.2